services:
  genshin-fe:
    image: ghcr.io/annisa-rachma/client-genshin:latest
    container_name: genshin-fe
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"

      # HTTPS router (websecure)
      - "traefik.http.routers.genshin-fe.rule=Host(`genshin.annisarachma.com`)"
      - "traefik.http.routers.genshin-fe.entrypoints=websecure"
      - "traefik.http.routers.genshin-fe.tls.certresolver=letsencrypt"

      # Optional: HTTP router that redirects to HTTPS
      - "traefik.http.routers.genshin-fe-http.rule=Host(`genshin.annisarachma.com`)"
      - "traefik.http.routers.genshin-fe-http.entrypoints=web"
      - "traefik.http.routers.genshin-fe-http.middlewares=redirect-to-https"

      # Define the service port (inside the container)
      - "traefik.http.services.genshin-fe.loadbalancer.server.port=80"

      # Redirect HTTP to HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  traefik_network:
    external: true
